name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  format-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Configure Git user identity
        run: |
          git config --global user.email "szewczykmateusz64@gmail.com"
          git config --global user.name "Mateusz Szewczyk"

      - name: Use GitHub Token
        run: echo ${{ secrets.GITHUB_TOKEN }}

      - name: Use GitHub Token
        run: echo ${{ secrets.MY_TOKEN_1 }}

      - name: Use GitHub Token
        run: echo ${{ secrets.PAT_TOKEN }}

      - name: Run Black and Commit
        run: |
          black .
          git add .
          git status
          git commit -m "Auto-commit changes" || true  # Continue even if there are no changes
          git log -n 1
          
          git push origin main
          
          
#          # Determine the branch and push accordingly
#          if [[ "$GITHUB_REF" == "refs/heads/main" ]]; then
#            git push origin main
#          elif [[ "$GITHUB_REF" == "refs/heads/dev" ]]; then
#            git push origin dev
#          else
#            echo "Skipping push for branch $GITHUB_REF"
#          fi
#        env:
#          GITHUB_TOKEN : ${{ secrets.MY_TOKEN_1 }}

  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get install xvfb

    - name: Run tests
      run: xvfb-run python -m pytest