name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  format-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Run Black
        run: |
          black .
          git add .
          git commit -m "Auto-format code with black" || true  # Continue even if there are no changes

          # Determine the branch and push accordingly
          if [[ "$GITHUB_REF" == "refs/heads/main" ]]; then
            git push origin main
          elif [[ "$GITHUB_REF" == "refs/heads/dev" ]]; then
            git push origin dev
          fi

  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get install xvfb

    - name: Run tests
      run: xvfb-run python -m pytest