name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  format-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Configure Git user identity
        run: |
          git config --global user.email "szewczykmateusz64@gmail.com"
          git config --global user.name "Mateusz Szewczyk"

      - name: Run Black and Commit
        run: |
          black .
          git add .
          git status
          git commit -m "Auto-commit changes" || true  # Continue even if there are no changes
          git log -n 1
          
          # Determine the branch and push accordingly
          if [[ "$GITHUB_REF" == "refs/heads/main" ]]; then
            git push origin main
          elif [[ "$GITHUB_REF" == "refs/heads/dev" ]]; then
            git push origin dev
          else
            echo "Skipping push for branch $GITHUB_REF"
          fi

  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get install xvfb

    - name: Run tests
      run: |
        xvfb-run python -m pytest

  build-docs:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'  # Only run when pushing to main

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Sphinx and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx
          pip install furo

      - name: Prepare branches
        run: |
          git config --global user.email "szewczykmateusz64@gmail.com"
          git config --global user.name "Mateusz Szewczyk"
          pwd
          git remote set-branches --add origin gh-pages
          git fetch origin gh-pages:gh-pages
          git reset --hard
          git checkout gh-pages
          if [ "$(ls -A)" ]; then
            # If there are files, delete them
            for i in $(ls); do
              rm -rf $i
            done
          
            # Check if there are any changes to commit
            if git status --porcelain | grep .; then
              git add .
              git commit -m "deleting old ghp"
            else
              echo "No changes to commit in gh-pages branch."
            fi
          else
            echo "No files to delete in gh-pages branch."
          fi
          git remote set-branches --add origin main
          git fetch origin main:main
          git checkout main
          git pull origin main

      - name: Build Sphinx documentation
        run: |
          cd docs
          make clean
          make html

      - name: Switch to gh-pages branch and copy files
        run: |
          git checkout -f gh-pages
          git checkout main docs/_build/html/*
          mv docs/_build/html/* .
          git checkout -f gh-pages

      - name: Commit and push to gh-pages
        run: |
          git add . 
          git commit -m "auto-generated ghp"
          git push -u origin gh-pages
